name: hw-succinct
version: '0.0.0.15'
synopsis: Conduits for tokenizing streams.
description: Please see README.md
category: Data, Conduit
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: MIT
github: haskell-works/hw-succinct
homepage: http://github.com/haskell-works/hw-succinct#readme
extra-source-files:
- README.md
ghc-options:
- -rtsopts
- -with-rtsopts=-N
- -Wall
- -O2
- -Wall
- -msse4.2
dependencies:
- base >=4 && <5
- attoparsec
- bytestring
- conduit
- containers
- hw-bits
- hw-conduit
- hw-diagnostics
- hw-json
- hw-parser
- hw-prim >=0.3.0.0
- hw-rankselect
- hw-xml
- mmap
- mono-traversable
- text
- vector
- word8
library:
  source-dirs: src
  exposed-modules:
  - HaskellWorks.Data.Succinct
